version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20   # REQUIRED for Angular 21
    commands:
      - npm install -g @angular/cli

  build:
    commands:
      - cd Frontend/testAws
      - npm install
      - ng build --configuration production

  post_build:
    commands:
      - aws s3 sync dist/testAws/browser/ s3://testaws-frontend --delete

artifacts:
  files:
    - Frontend/testAws/dist/testAws/browser/**/*
  discard-paths: yes
