version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24
    commands:
      - npm install -g @angular/cli

  build:
    commands:
      - cd Frontend/testAws
      - npm install
      - ng build --configuration production

artifacts:
  files:
    - Frontend/testAws/dist/testAws/browser/**/*
  discard-paths: yes
